### ISSUE TITLE
filter stage fails w division by zero?

### ISSUE THREAD

**Issue by dnil** [J35P312/FindSV#2]
Output vcf looks kind of ok, but filtered status is reported as "FAILED" in corresponding analysis file.

From ```FindTranslocations/filtered/sbatch_err/filter_P2271_201.err```:
```
Traceback (most recent call last):
  File "/pica/v16/b2015225_nobackup/private/sandbox/FindSV/programFiles/FindTranslocations/scipts/query_db.py", line 226, in <module>
    main(args)
  File "/pica/v16/b2015225_nobackup/private/sandbox/FindSV/programFiles/FindTranslocations/scipts/query_db.py", line 68, in main
    hit = isVariationInDB(allVariations, query,ratio)
  File "/pica/v16/b2015225_nobackup/private/sandbox/FindSV/programFiles/FindTranslocations/scipts/query_db.py", line 110, in isVariationInDB
    hit_tmp = isSameVariation(event, [chrA_start, chrA_end, chrB_start, chrB_end,variation_type],ratio)
  File "/pica/v16/b2015225_nobackup/private/sandbox/FindSV/programFiles/FindTranslocations/scipts/query_db.py", line 163, in isSameVariation
    overlapRatio=overlap_ratio(variation_start,variation_end,event_start,event_end)
  File "/pica/v16/b2015225_nobackup/private/sandbox/FindSV/programFiles/FindTranslocations/scipts/query_db.py", line 205, in overlap_ratio
    event_ratio=float(overlap_end-overlap_start+1)/float(region_end-region_start+1)
ZeroDivisionError: float division by zero
```

**Comment by J35P312** [comment]
That could happen if the start position of a variant is located after the stop position. I have fixed FindTranslocations so that it will not report variants that way(aswell as adding some exception handling to the query_db script). I have tested the fixed version of FIndTranslocations and the bug seem to be fixed. You should update and rerun FindTranslocations to make sure that you get the correct results, sorry for that =P. You can use this command to restart the FindTranslocations variant calling:
python FindSV.py --restart --caller FindTranslocations --vc
then start the pipeline:
python FindSV.py --run
